services:
  identidad:
    image: 172.31.36.189:5000/identidad:release
    env_file:
      - ./.env
    environment:
      - GIN_MODE=release
      - ENVIRONMENT=prod
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC_PERMISOS=prod.permisos
      - DB_SSLMODE=require
    ports:
      - target: 8080
        published: 8080
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

networks:
  default:
    name: bunna-prod-net
    external: true
