apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    url: http://clickhouse:8123
    secureJsonData:
      password: monitoreo_dev
    jsonData:
      server: clickhouse
      username: monitoreo
      defaultDatabase: bunna_monitoreo
      protocol: http
      port: 8123
      tlsSkipVerify: true
    isDefault: true
    editable: false
